# Jekyll - Configuration Settings
# see: https://github.com/mojombo/jekyll/wiki/Configuration
safe: false
auto: true
server: true
server_port: 9999
url: http://localhost:9999

source: ./
destination: ./_site
plugins: ./_plugins

future: false
lsi: false
pygments: true
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title/

#assets:
#  compress:
#    css:  sass

jekyll_models: [work]
jekyll_models_urls: rest-like

jekyll_models_sort_by: timestamp
jekyll_models_sort_descending: false

site_base: /

exclude:
  - README.md
  - config.rb
  - websector.de.iml
