# Default Configuration
# http://jekyllrb.com/docs/configuration/

source: .
destination: ./_site
plugins: ./_plugins

layouts: ./_layouts

exclude:
  - README.md
  - config.rb
  - websector.de.iml
  - wiki

future: false
highlighter: pygments

relative_permalinks: false

permalink: /blog/:year/:month/:day/:title/

markdown: rdiscount

safe: false
host: 0.0.0.0
port: 9999
baseurl: /
url: http://localhost:9999
lsi: false


sass:
  sass_dir: _sass
  style: :compressed
  sourcemap: true


# plugin settings

jekyll_models: [arbeiten]
jekyll_models_urls: rest-like

jekyll_models_sort_by: timestamp
jekyll_models_sort_descending: false

site_base: /




