# Jekyll - Configuration Settings
# see: https://github.com/mojombo/jekyll/wiki/Configuration
safe: false
auto : true
server : true
#baseurl: /
server_port : 9999,
url: http://localhost:9999

source:      ./src/jekyll
destination: ./public
plugins:     ./_plugins

future: false
lsi: false
pygments: true
markdown: maruku
permalink: /blog/:year/:month/:day/:title/

#exclude: ["README.md", "Gruntfile.js", "package.json", "websector.de.iml", "wordpress.xml", "src/styles", "src/scripts", "node_modules"]