# Jekyll - Configuration Settings
# see: https://github.com/mojombo/jekyll/wiki/Configuration
safe: false
auto: true
server: true
server_port: 9999
url: http://localhost:9999

source: ./src/jekyll
destination: ./public
plugins: ./_plugins

future: false
lsi: false
pygments: true
markdown: maruku
permalink: /blog/:year/:month/:day/:title/

#assets:
#  compress:
#    css:  sass

#asset_pipeline:
#  bundle: true            # Default = true
#  compress: false          # Default = true
#  output_path: assets/stylesheets     # Default = assets
#  display_path: assets/stylesheets       # Default = nil
#  gzip: false             # Default = false

jekyll_models: [work]
jekyll_models_urls: rest-like
site_base: /
