# Jekyll - Configuration Settings
# see: https://github.com/mojombo/jekyll/wiki/Configuration
sitename:
desc: Jens Krause - Portfolio
url: http://www.websector.de
permalink: /blog/:year/:month/:title.html
auto: true
exclude: ["README.md", "Gruntfile.js", "package.json", "websector.de.iml", "wordpress.xml", "src/styles", "src/scripts", "node_modules"]
pygments: true
plugins: _plugins
source: src/jekyll
destination: public